name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - name: Install
      run: yarn
    - name: Lint frontend
      run: yarn workspace frontend lint
    - name: Lint backend
      run: yarn workspace backend lint
#     - name: Test backend
#       run: yarn workspace backend test
    - name: Deploy Prisma service
      run: yarn workspace backend deploy:prisma
      env: 
        PRISMA_ENDPOINT: "https://dasher-9598c5ecbe.herokuapp.com/dasher/prod"
    
